public class Address {
    public enum ProvinceCode
    {
        // Canada Provinces
        [StringValue("AB"), Description("Alberta")] AB = 1,
        [StringValue("BC"), Description("British Colombia")] BC,
        [StringValue("MB"), Description("Manitoba")] MB,
        [StringValue("NB"), Description("New Brunswick")] NB,
        [StringValue("NL"), Description("Newfoundland and Labrador")] NL,
        [StringValue("NS"), Description("Nova Scotia")] NS,
        [StringValue("NT"), Description("Northwest Territories")] NT,
        [StringValue("NU"), Description("Nunavut")] NU,
        [StringValue("ON"), Description("Ontario")] ON,
        [StringValue("PE"), Description("Prince Edward Island")] PE,
        [StringValue("QC"), Description("Quebec")] QC,
        [StringValue("SK"), Description("Saskatchewan")] SK,
        [StringValue("YT"), Description("Yukon")] YT,

        // US States
        [StringValue("AL"), Description("Alabama")] AL,
        [StringValue("AK"), Description("Alaska")] AK,
        [StringValue("AR"), Description("Arkansas")] AR,
        [StringValue("AZ"), Description("Arizona")] AZ,
        [StringValue("CA"), Description("California")] CA,
        [StringValue("CO"), Description("Colorado")] CO,
        [StringValue("CT"), Description("Connecticut")] CT,
        [StringValue("DC"), Description("D.C.")] DC,
        [StringValue("DE"), Description("Delaware")] DE,
        [StringValue("FL"), Description("Florida")] FL,
        [StringValue("GA"), Description("Georgia")] GA,
        [StringValue("HI"), Description("Hawaii")] HI,
        [StringValue("IA"), Description("Iowa")] IA,
        [StringValue("ID"), Description("Idaho")] ID,
        [StringValue("IL"), Description("Illinois")] IL,
        [StringValue("IN"), Description("Indiana")] IN,
        [StringValue("KS"), Description("Kansas")] KS,
        [StringValue("KY"), Description("Kentucky")] KY,
        [StringValue("LA"), Description("Louisiana")] LA,
        [StringValue("MA"), Description("Massachusetts")] MA,
        [StringValue("MD"), Description("Maryland")] MD,
        [StringValue("ME"), Description("Maine")] ME,
        [StringValue("MI"), Description("Michigan")] MI,
        [StringValue("MN"), Description("Minnesota")] MN,
        [StringValue("MO"), Description("Missouri")] MO,
        [StringValue("MS"), Description("Mississippi")] MS,
        [StringValue("MT"), Description("Montana")] MT,
        [StringValue("NC"), Description("North Carolina")] NC,
        [StringValue("ND"), Description("North Dakota")] ND,
        [StringValue("NE"), Description("Nebraska")] NE,
        [StringValue("NH"), Description("New Hampshire")] NH,
        [StringValue("NJ"), Description("New Jersey")] NJ,
        [StringValue("NM"), Description("New Mexico")] NM,
        [StringValue("NV"), Description("Nevada")] NV,
        [StringValue("NY"), Description("New York")] NY,
        [StringValue("OK"), Description("Oklahoma")] OK,
        [StringValue("OH"), Description("Ohio")] OH,
        [StringValue("OR"), Description("Oregon")] OR,
        [StringValue("PA"), Description("Pennsylvania")] PA,
        [StringValue("RI"), Description("Rhode Island")] RI,
        [StringValue("SC"), Description("South Carolina")] SC,
        [StringValue("SD"), Description("South Dakota")] SD,
        [StringValue("TN"), Description("Tennessee")] TN,
        [StringValue("TX"), Description("Texas")] TX,
        [StringValue("UT"), Description("Utah")] UT,
        [StringValue("VA"), Description("Virginia")] VA,
        [StringValue("VT"), Description("Vermont")] VT,
        [StringValue("WA"), Description("Washington")] WA,
        [StringValue("WI"), Description("Wisconsin")] WI,
        [StringValue("WV"), Description("West Virginia")] WV,
        [StringValue("WY"), Description("Wyoming")] WY    
    }
}
