public class Address {
    
        public enum CountryCode
    {
        [StringValue("AD"), Description("Principat d'Andorra")] AD = 1,
        [StringValue("AE"), Description("United Arab Emirates")] AE,
        [StringValue("AF"), Description("Afghanistan")] AF,
        [StringValue("AG"), Description("Antigua and Barbuda")] AG,
        [StringValue("AL"), Description("Albania")] AL,
        [StringValue("AM"), Description("Armenia")] AM,
        [StringValue("AR"), Description("Argentina")] AR,
        [StringValue("AS"), Description("American Samoa")] AS,
        [StringValue("AT"), Description("Austria")] AT,
        [StringValue("AU"), Description("Australia")] AU,
        [StringValue("AW"), Description("Aruba Dutch Caribbean")] AW,
        [StringValue("BA"), Description("Bosnia")] BA,
        [StringValue("BD"), Description("Bangladesh")] BD,
        [StringValue("BE"), Description("Belgium")] BE,
        [StringValue("BF"), Description("Burkina Faso")] BF,
        [StringValue("BG"), Description("Bulgaria")] BG,
        [StringValue("BM"), Description("Bermuda")] BM, 
        [StringValue("BO"), Description("Bolivia")] BO,
        [StringValue("BQ"), Description("Bonaire/St Eus./Saba")] BQ,
        [StringValue("BR"), Description("Brazil")] BR,
        [StringValue("BS"), Description("Bahamas")] BS,
        [StringValue("BT"), Description("Bhutan")] BT,
        [StringValue("CA"), Description("Canada")] CA,
        [StringValue("CH"), Description("Switzerland")] CH,
        [StringValue("CL"), Description("Chile")] CL,
        [StringValue("CN"), Description("China")] CN,
        [StringValue("CO"), Description("Colombia")] CO,
        [StringValue("CR"), Description("Costa Rica")] CR,
        [StringValue("CY"), Description("Cyprus")] CY,
        [StringValue("CZ"), Description("Czech Republic")] CZ,
        [StringValue("DE"), Description("Germany")] DE,
        [StringValue("DK"), Description("Denmark")] DK,
        [StringValue("DM"), Description("Dominica")] DM,
        [StringValue("DO"), Description("Dominican Republic")] DO,
        [StringValue("EC"), Description("Ecuador")] EC,
        [StringValue("EE"), Description("Estonia")] EE,
        [StringValue("EG"), Description("Egypt")] EG,
        [StringValue("ES"), Description("Spain")] ES,
        [StringValue("FI"), Description("Finland")] FI,
        [StringValue("FJ"), Description("Fiji")] FJ,
        [StringValue("FR"), Description("France")] FR,
        [StringValue("GB"), Description("United Kingdom")] GB,
        [StringValue("GE"), Description("Georgia")] GE,
        [StringValue("GI"), Description("Gibraltar")] GI,
        [StringValue("GL"), Description("Greenland")] GL,
        [StringValue("GR"), Description("Greece")] GR,
        [StringValue("GT"), Description("Guatemala")] GT,
        [StringValue("GU"), Description("Guam")] GU,
        [StringValue("HK"), Description("Hong Kong")] HK,
        [StringValue("HN"), Description("Honduras")] HN,
        [StringValue("HR"), Description("Croatia")] HR,
        [StringValue("HT"), Description("Haiti")] HT,
        [StringValue("HU"), Description("Hungary")] HU,
        [StringValue("ID"), Description("Indonesia")] ID,
        [StringValue("IE"), Description("Ireland")] IE,
        [StringValue("IL"), Description("Israel")] IL,
        [StringValue("IN"), Description("India")] IN,
        [StringValue("IQ"), Description("Iraq")] IQ,
        [StringValue("IS"), Description("Iceland")] IS,
        [StringValue("IT"), Description("Italy")] IT,
        [StringValue("JM"), Description("Jamaica")] JM,
        [StringValue("JO"), Description("Jordan")] JO,
        [StringValue("JP"), Description("Japan")] JP,
        [StringValue("KG"), Description("Kyrgyzstan")] KG,
        [StringValue("KH"), Description("Cambodia")] KH,
        [StringValue("KN"), Description("Saint Kitts & Nevis")] KN,
        [StringValue("KP"), Description("Korea, D.P.R")] KP,
        [StringValue("KR"), Description("Korea")] KR,
        [StringValue("KW"), Description("Kuwait")] KW,
        [StringValue("KY"), Description("Cayman Islands")] KY,
        [StringValue("KZ"), Description("Kazakhstan")] KZ,
        [StringValue("LA"), Description("Laos")] LA,
        [StringValue("LB"), Description("Lebanon")] LB,
        [StringValue("LI"), Description("Liechtenstein")] LI,
        [StringValue("LT"), Description("Lithuania")] LT,
        [StringValue("LU"), Description("Luxemburg")] LU,
        [StringValue("LV"), Description("Latvia")] LV,
        [StringValue("MA"), Description("Morocco")] MA,
        [StringValue("MH"), Description("Marshall Islands")] MH,
        [StringValue("MK"), Description("Macedonia")] MK,
        [StringValue("MM"), Description("Myanmar")] MM,
        [StringValue("MP"), Description("Northern Mariana Is")] MP,
        [StringValue("MT"), Description("Malta")] MT,
        [StringValue("MX"), Description("Mexico")] MX,
        [StringValue("MY"), Description("Malaysia")] MY,
        [StringValue("NI"), Description("Nicaragua")] NI,
        [StringValue("NL"), Description("Norway")] NL,
        [StringValue("NZ"), Description("New Zealand")] NZ,
        [StringValue("PA"), Description("Panama")] PA,
        [StringValue("PE"), Description("Peru")] PE,
        [StringValue("PG"), Description("Papua New Guinea")] PG,
        [StringValue("PH"), Description("Philippines")] PH,
        [StringValue("PK"), Description("Pakistan")] PK,
        [StringValue("PL"), Description("Poland")] PL,
        [StringValue("PR"), Description("Puerto Rico")] PR,
        [StringValue("PT"), Description("Portugal")] PT,
        [StringValue("PY"), Description("Paraguay")] PY,
        [StringValue("RO"), Description("Romania")] RO,
        [StringValue("RS"), Description("Serbia")] RS,
        [StringValue("RU"), Description("Russia")] RU,
        [StringValue("SA"), Description("Saudi Arabia")] SA,
        [StringValue("SE"), Description("Sweden")] SE,
        [StringValue("SG"), Description("Singapore")] SG,
        [StringValue("SI"), Description("Slovenia")] SI,
        [StringValue("SK"), Description("Slovakia")] SK,
        [StringValue("SL"), Description("Sierra Leon")] SL,
        [StringValue("SV"), Description("El Salvador")] SV,
        [StringValue("SZ"), Description("Swaziland")] SZ,
        [StringValue("TH"), Description("Thailand")] TH,
        [StringValue("TN"), Description("Tunisia")] TN,
        [StringValue("TR"), Description("Turkey")] TR,
        [StringValue("TT"), Description("Trinidad & Tobago")] TT,
        [StringValue("TW"), Description("Taiwan")] TW,
        [StringValue("TZ"), Description("Tanzania")] TZ,
        [StringValue("UA"), Description("Ukraine")] UA,
        [StringValue("US"), Description("United States")] US,
        [StringValue("UY"), Description("Uruguay")] UY,
        [StringValue("VE"), Description("Venezuela")] VE,
        [StringValue("VG"), Description("British Virgin Island")] VG,
        [StringValue("VI"), Description("US Virgin Islands")] VI,
        [StringValue("VN"), Description("Vietnam")] VN,
        [StringValue("ZA"), Description("South Africa")] ZA
    }
    
    public enum ProvinceCode
    {
        // Canada Provinces
        [StringValue("AB"), Description("Alberta")] AB = 1,
        [StringValue("BC"), Description("British Colombia")] BC,
        [StringValue("MB"), Description("Manitoba")] MB,
        [StringValue("NB"), Description("New Brunswick")] NB,
        [StringValue("NL"), Description("Newfoundland and Labrador")] NL,
        [StringValue("NS"), Description("Nova Scotia")] NS,
        [StringValue("NT"), Description("Northwest Territories")] NT,
        [StringValue("NU"), Description("Nunavut")] NU,
        [StringValue("ON"), Description("Ontario")] ON,
        [StringValue("PE"), Description("Prince Edward Island")] PE,
        [StringValue("QC"), Description("Quebec")] QC,
        [StringValue("SK"), Description("Saskatchewan")] SK,
        [StringValue("YT"), Description("Yukon")] YT,

        // US States
        [StringValue("AL"), Description("Alabama")] AL,
        [StringValue("AK"), Description("Alaska")] AK,
        [StringValue("AR"), Description("Arkansas")] AR,
        [StringValue("AZ"), Description("Arizona")] AZ,
        [StringValue("CA"), Description("California")] CA,
        [StringValue("CO"), Description("Colorado")] CO,
        [StringValue("CT"), Description("Connecticut")] CT,
        [StringValue("DC"), Description("D.C.")] DC,
        [StringValue("DE"), Description("Delaware")] DE,
        [StringValue("FL"), Description("Florida")] FL,
        [StringValue("GA"), Description("Georgia")] GA,
        [StringValue("HI"), Description("Hawaii")] HI,
        [StringValue("IA"), Description("Iowa")] IA,
        [StringValue("ID"), Description("Idaho")] ID,
        [StringValue("IL"), Description("Illinois")] IL,
        [StringValue("IN"), Description("Indiana")] IN,
        [StringValue("KS"), Description("Kansas")] KS,
        [StringValue("KY"), Description("Kentucky")] KY,
        [StringValue("LA"), Description("Louisiana")] LA,
        [StringValue("MA"), Description("Massachusetts")] MA,
        [StringValue("MD"), Description("Maryland")] MD,
        [StringValue("ME"), Description("Maine")] ME,
        [StringValue("MI"), Description("Michigan")] MI,
        [StringValue("MN"), Description("Minnesota")] MN,
        [StringValue("MO"), Description("Missouri")] MO,
        [StringValue("MS"), Description("Mississippi")] MS,
        [StringValue("MT"), Description("Montana")] MT,
        [StringValue("NC"), Description("North Carolina")] NC,
        [StringValue("ND"), Description("North Dakota")] ND,
        [StringValue("NE"), Description("Nebraska")] NE,
        [StringValue("NH"), Description("New Hampshire")] NH,
        [StringValue("NJ"), Description("New Jersey")] NJ,
        [StringValue("NM"), Description("New Mexico")] NM,
        [StringValue("NV"), Description("Nevada")] NV,
        [StringValue("NY"), Description("New York")] NY,
        [StringValue("OK"), Description("Oklahoma")] OK,
        [StringValue("OH"), Description("Ohio")] OH,
        [StringValue("OR"), Description("Oregon")] OR,
        [StringValue("PA"), Description("Pennsylvania")] PA,
        [StringValue("RI"), Description("Rhode Island")] RI,
        [StringValue("SC"), Description("South Carolina")] SC,
        [StringValue("SD"), Description("South Dakota")] SD,
        [StringValue("TN"), Description("Tennessee")] TN,
        [StringValue("TX"), Description("Texas")] TX,
        [StringValue("UT"), Description("Utah")] UT,
        [StringValue("VA"), Description("Virginia")] VA,
        [StringValue("VT"), Description("Vermont")] VT,
        [StringValue("WA"), Description("Washington")] WA,
        [StringValue("WI"), Description("Wisconsin")] WI,
        [StringValue("WV"), Description("West Virginia")] WV,
        [StringValue("WY"), Description("Wyoming")] WY    
    }
}
